<a href="https://colab.research.google.com/github/hernans7/mis433/blob/main/SHR_assignment_python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? Sam
Welcome, Sam!


In [ ]:
# complete your program here
f = float(input('Please enter the temperature in Fahrenheit: '))

print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 40
40.0
40.0F is 4.444444444444445 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [ ]:
c =float(input('Please enter the temperature in Celcius: '))

print(c)

#Fahrenheit = (Celcius + 32)/5/9
f = (c * 9/5) + 32

print(f'{c}C is {f} in Fahrenheit. ')

Please enter the temperature in Celcius: 60
60.0
60.0C is 140.0 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [ ]:
# complete your program here

choice = input("Type 'C' to convert to Celcius or type 'F' to convert to Fahrenheit: ")

if choice == 'C':
	f = float(input('Please enter the temperature in Fahrenheit: '))
	print(f)
	c = (f - 32) * 5/9
	print(f'{f}F is {c} in Celsius. ')

elif choice == 'F':
	c = float(input('Please enter the temperature in Celcius'))
	print(c)
	f = (c * 9/5) + 32
	print(f'{c}C is {f} in Fahrenheit. ')

Type 'C' to convert to Celcius or type 'F' to convert to Fahrenheit: C
Please enter the temperature in Fahrenheit: 140
140.0
140.0F is 60.0 in Celsius. 


## Question 2

Have some fun with strings.

In [ ]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [ ]:
# Find the length of this sentence.
print (len(sentence))

48


In [ ]:
# Convert the whole string to lower case.
lower = sentence.lower()
print(lower)

talk is cheap. show me the code - linus torvalds


In [ ]:
# Extract a substring from the 10th character from left to the 10th character from right.
substring = sentence[10:-10]
print(substring)

eap. Show me the code - Linu


In [ ]:
# Split the sentence into a list of substrings by space ' '.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"
split = sentence.split()
print(split)

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [ ]:
import re

sentence = "Talk is cheap. Show me the code - Linus Torvalds"
# Given the sentence, output a list of words in lowercase (without punctuations).

# Convert to lowercase
lower = sentence.lower()

# Remove punctuation and split into words
# Use a regex to replace anything that's not a letter or space with an empty string
no_punct_sentence = re.sub(r'[^a-z\s]', '', lower)
word_list = no_punct_sentence.split()

print(word_list)

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [ ]:
# Count the total number of vowels in the sentence.
vowels = 'aeiou'
count = 0 # Initialize count to 0
for v in vowels:
   print(v, sentence.lower() .count(v))
   count+= sentence.lower() .count(v)
print(count)

a 3
e 4
i 2
o 3
u 1
13


In [ ]:
# Find the positions (indexes) of all vowels in the sentence.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"
vowels = 'aeiou'
for i in range(len(sentence)):
    if sentence[i] in vowels:
        print(f"Vowel '{sentence[i]}' found at index {i}")

Vowel 'a' found at index 1
Vowel 'i' found at index 5
Vowel 'e' found at index 10
Vowel 'a' found at index 11
Vowel 'o' found at index 17
Vowel 'e' found at index 21
Vowel 'e' found at index 25
Vowel 'o' found at index 28
Vowel 'e' found at index 30
Vowel 'i' found at index 35
Vowel 'u' found at index 37
Vowel 'o' found at index 41
Vowel 'a' found at index 44


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [ ]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = [0, 1, 8, 27, 64]
for i in range(5):
    cubes.append(i**3)
print(cubes)


[0, 1, 8, 27, 64, 0, 1, 8, 27, 64]


In [ ]:
# Use list comprehension to create the same list
cubes = [i**3 for i in range(5)]
print(cubes)


[0, 1, 8, 27, 64]


In [ ]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
vowels = 'aeiou'
vowels_index = [i for i in range(len(sentence)) if sentence[i] in vowels]
print(vowels_index)


[1, 3, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47]


In [ ]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = input('How many numbers do you want? ')
n = int(n)
# add your code here
if n <= 0:
    fibonacci = []
elif n == 1:
    fibonacci = [0]
elif n == 2:
    fibonacci = [0, 1]
else:
    fibonacci = [0, 1]
    while len(fibonacci) < n:
        fibonacci.append(fibonacci[-1] + fibonacci[-2])

print(fibonacci)


How many numbers do you want? 20
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [ ]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {
    'Pfizer': 0.95,
    'Moderna': 0.95,
    'AstraZeneca': 0.72,
    'Johnson & Johnson': 0.66
}

In [ ]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v_dict[v])


Which vaccine? Moderna
0.95


In [ ]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = 0.914
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [ ]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict["Sinovac"] = 0.5038
print(v_dict)



{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914, 'Sinovac': 0.5038}


In [ ]:
# Print vaccines with efficacy lower than 90%.
for v in v_dict:
    if v_dict[v] < 0.90:
        print(v)

AstraZeneca
Johnson & Johnson
Sinovac


In [ ]:
# delete the Sinovac vaccine from the dictionary.
del v_dict["Sinovac"]
print(v_dict)


{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [ ]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

count = {}
for char in sentence:
    if char != ' ':
        if char in count:
            count[char] += 1
        else:
            count[char] = 1
print(count)

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# add your code here

# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}
{}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [ ]:
import numpy as np

In [ ]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
even_numbers = np.arange(2, 41, 2)
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [ ]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
odd_numbers = np.arange(1, 41, 2)
print(odd_numbers)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [ ]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.array([])
np.arange(0, 100).reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, size=(10, 10))
M.shape == (10, 10)
print(M)

[[-1.2329677  -0.3623057  -0.29542162  1.35732372  2.41325966  0.08313391
  -0.18978441 -0.24168752 -0.7096613   1.32237134]
 [-0.11404279 -0.14266919  0.30813177  1.02019739 -1.15239689 -1.36388802
  -0.21626243 -1.00097282  0.46013617  0.92710895]
 [-0.07732686 -0.13495476 -1.1027463  -0.64121046  0.43617273  0.28751498
  -1.56985431  1.88968762  0.0260519   1.0541636 ]
 [ 0.39309874  0.74349402 -0.35279452  0.26101377  1.05457259  0.39830998
  -1.27106478 -0.96642739 -1.11884068  0.00459232]
 [-0.07102495  0.07781338  1.00745387 -0.56428426  0.84868778  1.44302295
   0.05129658  0.7293126   1.87037829  2.05440569]
 [ 0.76171775 -0.73191542  0.08924682 -2.08294072  0.35675441  0.1152186
  -2.17337475 -0.07762796 -1.75133305 -0.00720083]
 [-1.67493922 -0.80282478  0.64908307  0.39679239 -1.23568689 -0.21615264
  -1.2499633  -1.61381782 -1.21924352  1.09053718]
 [-1.08765325  2.82396494 -0.03546489 -0.14927941 -1.00972475 -0.53559956
   0.43719965  0.64558559 -0.11373248 -1.08478938]
 

In [ ]:
# Count the numbers in M with an absolute value greater than 1.
count = np.sum(np.abs(M) > 1)
print(count)

36


In [ ]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = int(input('Row count: '))


# Input the number of rows (input another integer >= 3)
c = int(input('column count: '))

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, size=(r, c))
print(arr)

Row count: 20
column count: 10
[[17 17 16 10 10 11 15 18 11 15]
 [16 13 11 13 18 14 15 15 13 10]
 [18 16 11 15 10 10 11 19 18 14]
 [10 13 18 11 17 15 14 13 16 10]
 [14 14 14 19 12 15 12 16 12 12]
 [13 10 15 17 15 18 13 10 17 16]
 [10 13 17 18 14 19 19 16 15 19]
 [15 15 17 13 10 10 12 15 13 17]
 [12 19 18 11 16 16 13 10 16 14]
 [16 10 19 14 15 11 14 15 12 17]
 [14 14 14 15 17 14 13 16 15 14]
 [10 14 14 18 13 15 18 10 17 13]
 [17 18 10 11 14 11 13 12 15 11]
 [13 12 11 18 18 10 19 11 11 10]
 [16 11 16 14 14 11 17 11 11 15]
 [13 19 12 12 19 19 17 12 17 17]
 [12 15 15 12 19 10 19 12 19 19]
 [18 11 16 19 15 10 18 15 18 10]
 [19 14 11 16 19 17 15 12 19 15]
 [14 18 16 12 11 15 18 13 17 10]]


In [ ]:
# output the element in the first row and the third column
arr = np.random.randint(10, 20, size=(r, c))
print(arr[0, 2])

17


In [ ]:
# output the element in the second row and the last column
arr = np.random.randint(10, 20, size=(r, c))
print(arr[1, -1])

10


In [ ]:
# output the second row of the array
arr = np.random.randint(10, 20, size=(r, c))
print(arr[1, :])

[18 10 13 12 18 17 19 13 10 12]


In [ ]:
# output the second last row of the array
arr = np.random.randint(10, 20, size=(r, c))
print(arr[-2, :])

[10 15 18 11 14 13 18 16 19 18]


In [ ]:
# output the second column of the array
arr = np.random.randint(10, 20, size=(r, c))
print(arr[:, 1])

[14 13 14 14 13 16 19 15 14 14 16 10 16 17 10 15 18 13 17 15]


In [ ]:
# output the second last column of the array
arr = np.random.randint(10, 20, size=(r, c))
print(arr[:, -2])

[15 12 11 16 11 13 16 18 14 11 18 11 10 15 12 19 15 15 11 15]


In [ ]:
# output the upper-left 3x3 sub-array
arr = np.random.randint(10, 20, size=(r, c))
print(arr[:3, :3])

[[18 15 13]
 [12 15 10]
 [16 13 12]]


In [ ]:
# output the bottom-left 3x3 sub-array
arr = np.random.randint(10, 20, size=(r, c))
print(arr[-3:, :3])

[[19 13 13]
 [19 15 18]
 [16 19 13]]


In [ ]:
# output the upper-right 3x3 sub-array
arr = np.random.randint(10, 20, size=(r, c))
print(arr[:3, -3:])

[[19 15 14]
 [16 16 12]
 [14 13 17]]


In [ ]:
# output the bottom-right 3x3 sub-array
arr = np.random.randint(10, 20, size=(r, c))
print(arr[-3:, -3:])

[[12 12 11]
 [15 18 19]
 [18 17 16]]


In [ ]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1, 51)
print(A)
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# third row :
# fifth row: [41,...,50]
A = A.reshape(5, 10)
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [ ]:
# add a row [51,...,60] to A
A = np.append(A, np.arange(51, 61).reshape(1, 10), axis=0)
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [ ]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A = np.arange(1, 61).reshape(6, 10)
A1 = A[:3, :]
A2 = A[3:, :]
print(A1)
print(A2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [ ]:
# Add 10 to each element of A
A = A + 10
print(A)

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [ ]:
# Calculate the square root of each element in A
A = np.sqrt(A)
print(A)

[[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
  4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
  5.19615242 5.29150262 5.38516481 5.47722558]
 [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
  6.08276253 6.164414   6.244998   6.32455532]
 [6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
  6.8556546  6.92820323 7.         7.07106781]
 [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
  7.54983444 7.61577311 7.68114575 7.74596669]
 [7.81024968 7.87400787 7.93725393 8.         8.06225775 8.1240384
  8.18535277 8.24621125 8.30662386 8.36660027]]


In [ ]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape == (10, 10)
print(M)

[[-1.2329677  -0.3623057  -0.29542162  1.35732372  2.41325966  0.08313391
  -0.18978441 -0.24168752 -0.7096613   1.32237134]
 [-0.11404279 -0.14266919  0.30813177  1.02019739 -1.15239689 -1.36388802
  -0.21626243 -1.00097282  0.46013617  0.92710895]
 [-0.07732686 -0.13495476 -1.1027463  -0.64121046  0.43617273  0.28751498
  -1.56985431  1.88968762  0.0260519   1.0541636 ]
 [ 0.39309874  0.74349402 -0.35279452  0.26101377  1.05457259  0.39830998
  -1.27106478 -0.96642739 -1.11884068  0.00459232]
 [-0.07102495  0.07781338  1.00745387 -0.56428426  0.84868778  1.44302295
   0.05129658  0.7293126   1.87037829  2.05440569]
 [ 0.76171775 -0.73191542  0.08924682 -2.08294072  0.35675441  0.1152186
  -2.17337475 -0.07762796 -1.75133305 -0.00720083]
 [-1.67493922 -0.80282478  0.64908307  0.39679239 -1.23568689 -0.21615264
  -1.2499633  -1.61381782 -1.21924352  1.09053718]
 [-1.08765325  2.82396494 -0.03546489 -0.14927941 -1.00972475 -0.53559956
   0.43719965  0.64558559 -0.11373248 -1.08478938]
 

In [ ]:
# Print the mean, standard devietion of all numbers in M
print(np.mean(M))
print(np.std(M))

-0.030097835560709826
1.0126765840238436


In [ ]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print(np.max(M))
print(np.percentile(M, 75))
print(np.median(M))
print(np.percentile(M, 25))
print(np.min(M))

2.823964941280832
0.504096737629122
-0.07417590410175609
-0.7730820239098701
-2.173374754777465
